Class %pkg.isc.rest.openAPI.model.responseReference Extends (%pkg.isc.rest.openAPI.model.responseOrReference, %pkg.isc.rest.openAPI.model.reference)
{

Storage Default
{
<Data name="ResponseReferenceDefaultData">
<Subscript>"ResponseReference"</Subscript>
<Value name="1">
<Value>Ref</Value>
</Value>
</Data>
<DefaultData>ResponseReferenceDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}

